# LanDiscord 플러그인의 컨피그입니다. 주석에 * 이 있는 항목은 필수로 설정해주세요.
# 보다 자세한 설명과 예시는 깃허브 위키에 만들 예정입니다.
# ~ 는 임시 표기로, 지우고 값을 입력해주세요.
discord:
  # 사용할 봇의 토큰*
  token: ~
  # 웹훅의 기본 이름
  webhookName: ~
  # 봇과 웹훅이 출력될 채널 목록
  channel:
    - id: ~
      # 아래 두 항목은 각각 봇과 웹훅이 채널에 출력할 내용을 정합니다.
      # 아래 목록을 보고, 원하는 항목을 모두 적어주세요.
      # serverChat - 서버 채팅 출력
      # playerIO - 플레이어 접속 알림
      # serverConnect - 디스코드와 서버 연결 메시지
      botUsage: ~
      webhookUsage: ~